### ISSUE TITLE
ecdsa invalid hex

### ISSUE THREAD

**Issue by Hey** [vultisig/airdrop-registry#2]
Why in a vault backup is ecdsa 66 length (invalid hex) while eddsa is a valid hex (64 length)?

**Comment by johnnyluo** [comment]
Those public keys are valid for sure , because it can be used by both Android and IOS apps, the reason is 
1.EdDSA (Edwards Curve Digital Signature Algorithm): For EdDSA, particularly when using Curve25519 or Ed25519, the public key is represented by a single coordinate (the (x) coordinate for Curve25519, and the (y) coordinate for Ed25519), because the other coordinate can be deterministically computed from it. The public key is typically 32 bytes long when serialized because it only needs to store one 256-bit coordinate.  
2.ECDSA (Elliptic Curve Digital Signature Algorithm): In ECDSA, when public keys are compressed, they include one coordinate (either (x) or (y)) and an additional byte to indicate which of the two possible (y) coordinates is the correct one (since for every (x) value there are two possible (y) values). This is why compressed ECDSA public keys are 33 bytes long: 32 bytes for the coordinate and 1 byte for the indication of the (y) coordinate.
